"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.LuhnAlgorithm = exports.isValidVatNumber = exports.isValidTaxNumber = exports.isValidNumber = exports.isValidNonGeographicNumber = exports.isValidGeographicNumber = exports.isValidIdNumber = exports.isValidCellphoneNumber = void 0;
const cellphone_1 = __importDefault(require("./PhoneNumber/cellphone"));
exports.isValidCellphoneNumber = cellphone_1.default;
const index_1 = __importDefault(require("./IdentificationNumber/index"));
exports.isValidIdNumber = index_1.default;
const geographic_1 = __importDefault(require("./PhoneNumber/geographic"));
exports.isValidGeographicNumber = geographic_1.default;
const nonGeographic_1 = __importDefault(require("./PhoneNumber/nonGeographic"));
exports.isValidNonGeographicNumber = nonGeographic_1.default;
const geoOrNonGeo_1 = __importDefault(require("./PhoneNumber/geoOrNonGeo"));
exports.isValidNumber = geoOrNonGeo_1.default;
const index_2 = __importDefault(require("./TaxNumber/index"));
exports.isValidTaxNumber = index_2.default;
const index_3 = __importDefault(require("./VatNumber/index"));
exports.isValidVatNumber = index_3.default;
const index_4 = __importDefault(require("./LuhnAlgorithm/index"));
exports.LuhnAlgorithm = index_4.default;
