"use strict";
// // Work in Progress
// const numberlookup = (phonenumber: string) => {};
// // taken from the electronic communications act: regulations: numbering plan: https://www.icasa.org.za/uploads/files/numberingplanreg.pdf
// const geographicregions = [
//   { locations: ["johannesburg"], code: ["010", "011"], provinces: ["gauteng"] },
//   { locations: ["tshwane", "pretoria"], code: ["012"], provinces: ["gauteng"] },
//   {
//     locations: [
//       "mpumalanga",
//       "northern mpumalanga",
//       "western mpumalanga",
//       "middelburg",
//       "witbank",
//       "nelspruit",
//     ],
//     code: ["013"],
//     provinces: ["mpumalanga"],
//   },
//   {
//     locations: [
//       "north west",
//       "northern north west",
//       "limpopo",
//       "southern limpopo",
//       "western limpopo",
//       "rustenburg",
//       "nylstroom",
//     ],
//     code: ["014"],
//     provinces: ["north west", "limpopo"],
//   },
//   {
//     locations: ["limpopo", "northern limpopo", "eastern limpopo", "polokwane"],
//     code: ["015"],
//     provinces: ["limpopo"],
//   },
//   {
//     locations: ["vaal triangle", "vereeniging", "vanderbijlpark", "sasolburg"],
//     code: ["016"],
//     provinces: ["gauteng", "free state"],
//   },
//   {
//     locations: ["southern mpumalanga", "mpumalanga", "ermelo"],
//     code: ["017"],
//     provinces: ["mpumalanga"],
//   },
//   {
//     locations: [
//       "southern north west",
//       "north west",
//       "potchefstroom",
//       "klerksdorp",
//     ],
//     code: ["018"],
//     provinces: ["north west"],
//   },
//   {
//     locations: [],
//     code: ["019"],
//     provinces: [],
//   },
//   {
//     locations: [],
//     code: ["020"],
//     provinces: [],
//   },
//   {
//     locations: ["cape town", "stellenbosch", "somerset west", "gordons bay"],
//     code: ["021"],
//     provinces: ["western cape"],
//   },
//   {
//     locations: [
//       "western coast of western cape",
//       "west coast",
//       "boland",
//       "malmesbury",
//     ],
//     code: ["022"],
//     provinces: ["western cape"],
//   },
//   {
//     locations: ["karoo", "worcester", "beaufort west"],
//     code: ["023"],
//     provinces: ["western cape"],
//   },
//   {
//     locations: [],
//     code: ["024"],
//     provinces: [],
//   },
//   {
//     locations: [],
//     code: ["025"],
//     provinces: [],
//   },
//   {
//     locations: [],
//     code: ["026"],
//     provinces: [],
//   },
//   {
//     locations: [
//       "namaqualand",
//       "vredendal",
//       "calvinia",
//       "clanwilliam",
//       "springbok",
//       "alexander bay",
//       "port nolloth",
//     ],
//     code: ["027"],
//     provinces: ["western cape", "northern cape"],
//   },
//   {
//     locations: [
//       "southern coast of western cape",
//       "swellendam",
//       "caledon",
//       "hermanus",
//     ],
//     code: ["028"],
//     provinces: ["western cape"],
//   },
//   {
//     locations: [],
//     code: ["029"],
//     provinces: [],
//   },
//   {
//     locations: [],
//     code: ["030"],
//     provinces: [],
//   },
//   {
//     locations: ["durban"],
//     code: ["031"],
//     provinces: ["kwazulu natal"],
//   },
//   {
//     locations: ["kwazulu natal central coast", "kwazulu natal", "stanger"],
//     code: ["032"],
//     provinces: ["kwazulu natal"],
//   },
//   {
//     locations: ["kwazulu natal midlands", "pietermaritzburg"],
//     code: ["033"],
//     provinces: ["kwazulu natal"],
//   },
//   {
//     locations: ["northern kwazulu natal", "vryheid", "newcastle"],
//     code: ["034"],
//     provinces: ["kwazulu natal"],
//   },
//   {
//     locations: ["zululand", "st. lucia", "richards bay"],
//     code: ["035"],
//     provinces: ["kwazulu natal"],
//   },
//   {
//     locations: ["drakensberg", "ladysmith"],
//     code: ["036"],
//     provinces: ["kwazulu natal"],
//   },
//   {
//     locations: [],
//     code: ["037"],
//     provinces: [],
//   },
//   {
//     locations: [],
//     code: ["038"],
//     provinces: [],
//   },
//   {
//     locations: [
//       "eastern pondoland",
//       "southern coast of kwazulu natal",
//       "port shepstone",
//     ],
//     code: ["039"],
//     provinces: ["eastern cape", "kwazulu natal"],
//   },
//   {
//     locations: ["bhisho"],
//     code: ["040"],
//     provinces: ["eastern cape"],
//   },
//   {
//     locations: ["port elizabeth", "uitenhage"],
//     code: ["041"],
//     provinces: ["eastern cape"],
//   },
//   {
//     locations: ["southern eastern cape", "central eastern cape", "humansdorp"],
//     code: ["042"],
//     provinces: ["eastern cape"],
//   },
//   {
//     locations: ["east london"],
//     code: ["043"],
//     provinces: ["east london"],
//   },
//   {
//     locations: [
//       "garden route",
//       "oudtshoorn",
//       "knysna",
//       "plettenberg bay",
//       "mossel bay",
//       "george",
//     ],
//     code: ["044"],
//     provinces: ["western cape", "eastern cape"],
//   },
//   {
//     locations: ["northern eastern cape", "eastern eastern cape", "queenstown"],
//     code: ["045"],
//     provinces: ["eastern cape"],
//   },
//   {
//     locations: ["southern eastern cape", "eastern eastern cape", "grahamstown"],
//     code: ["046"],
//     provinces: ["eastern cape"],
//   },
//   {
//     locations: ["eastern eastern cape", "mthatha"],
//     code: ["047"],
//     provinces: ["eastern eastern cape"],
//   },
//   {
//     locations: ["northern eastern cape", "steynsburg"],
//     code: ["048"],
//     provinces: ["eastern cape"],
//   },
//   {
//     locations: ["western eastern cape", "graaff-reinet"],
//     code: ["049"],
//     provinces: ["eastern cape"],
//   },
//   {
//     locations: [],
//     code: ["050"],
//     provinces: [],
//   },
//   {
//     locations: [
//       "southern free state",
//       "central free state",
//       "bloemfontein",
//       "far eastern eastern cape",
//       "aliwal north",
//     ],
//     code: ["051"],
//     provinces: ["free state", "eastern cape"],
//   },
//   {
//     locations: [],
//     code: ["052"],
//     provinces: [],
//   },
//   {
//     locations: ["eastern northern cape", "kimberley", "far western north west"],
//     code: ["053"],
//     provinces: ["northern cape", "north west"],
//   },
//   {
//     locations: ["gordonia", "upington"],
//     code: ["054"],
//     provinces: ["northern cape"],
//   },
//   {
//     locations: [],
//     code: ["055"],
//     provinces: [],
//   },
//   {
//     locations: ["northern free state", "kroonstad"],
//     code: ["056"],
//     provinces: ["free state"],
//   },
//   {
//     locations: ["free state goldfields", "welkom"],
//     code: ["057"],
//     provinces: ["free state"],
//   },
//   {
//     locations: ["eastern free state", "bethlehem"],
//     code: ["058"],
//     provinces: [],
//   },
//   {
//     locations: [],
//     code: ["059"],
//     provinces: [],
//   },
// ];
// const localarea = [
//   { location: "aberdeen", code: "049" },
//   { location: "aberfeldy", code: "058" },
//   { location: "acornhoek", code: "013" },
//   { location: "addo", code: "042" },
//   { location: "adelaide", code: "046" },
//   { location: "aggeneys", code: "054" },
//   { location: "albertinia", code: "028" },
//   { location: "alberton", code: "011" },
//   { location: "alettasrus", code: "053922" },
//   { location: "alexander bay", code: "027" },
//   { location: "alexandria", code: "046" },
//   { location: "alice", code: "040" },
//   { location: "alicedale", code: "042" },
//   { location: "aliwal north", code: "051" },
//   { location: "allanridge", code: "057" },
//   { location: "alldays", code: "015" },
//   { location: "alma", code: "014" },
//   { location: "amalia", code: "053" },
//   { location: "amandelbult", code: "014" },
//   { location: "amanzimtoti", code: "031" },
//   { location: "amatikulu", code: "035" },
//   { location: "amersfoort", code: "017" },
//   { location: "amsterdam", code: "017" },
//   { location: "anerley", code: "039" },
//   { location: "apel", code: "015" },
//   { location: "arabiedam", code: "013" },
//   { location: "arboretum", code: "035" },
//   { location: "arlington", code: "058" },
//   { location: "arlington farm lines / plaaslyne", code: "05602" },
//   { location: "arnot", code: "013" },
//   { location: "arthur stone", code: "013" },
//   { location: "ashton", code: "023" },
//   { location: "askham", code: "054" },
//   { location: "askham farm lines / plaaslyne", code: "0545112" },
//   { location: "atamelang", code: "018" },
//   { location: "atlantis", code: "021" },
//   { location: "atok", code: "015" },
//   { location: "atteridgeville", code: "012" },
//   { location: "attiesplaas", code: "05462" },
//   { location: "auckland park", code: "011" },
//   { location: "auckland park", code: "010" },
//   { location: "augrabies", code: "054" },
//   { location: "aurora", code: "022" },
//   { location: "austin's post", code: "051742" },
//   { location: "avontuur", code: "044" },
//   { location: "babanango", code: "035" },
//   { location: "babethu", code: "013" },
//   { location: "badplaas", code: "017" },
//   { location: "bahlalerwa", code: "014" },
//   { location: "bakenberg", code: "015" },
//   { location: "bakone", code: "015" },
//   { location: "baleema", code: "014" },
//   { location: "balfour (ec/ok)", code: "040" },
//   { location: "balfour (m)", code: "017" },
//   { location: "ballito", code: "032" },
//   { location: "balmoral", code: "013" },
//   { location: "bamaaka", code: "014" },
//   { location: "bamokgoko", code: "012" },
//   { location: "barberton", code: "013" },
//   { location: "barkly west", code: "053" },
//   { location: "barkly east", code: "045" },
//   { location: "barrydale", code: "028" },
//   { location: "bathurst", code: "046" },
//   { location: "beaufort west", code: "023" },
//   { location: "bedford", code: "046" },
//   { location: "beeldhouwersfontein", code: "049" },
//   { location: "beestekraal", code: "012" },
//   { location: "beitbridge", code: "015" },
//   { location: "bela-bela", code: "014" },
//   { location: "belfast", code: "013" },
//   { location: "bellville", code: "021" },
//   { location: "belmont", code: "053" },
//   { location: "benoni", code: "011" },
//   { location: "bergville", code: "036" },
//   { location: "bergvliet", code: "021" },
//   { location: "berlin", code: "043" },
//   { location: "bethal", code: "017" },
//   { location: "bethanie", code: "012" },
//   { location: "bethlehem", code: "058" },
//   { location: "bethulie", code: "051" },
//   { location: "bethulie farm lines / plaaslyne", code: "051762" },
//   { location: "betty's bay", code: "028" },
//   { location: "bhisho", code: "040" },
//   { location: "bholothwa", code: "047" },
//   { location: "biesiesvlei", code: "018" },
//   { location: "biesiesvlei farm lines / plaaslyne", code: "014452" },
//   { location: "birds river", code: "045" },
//   { location: "bisho", code: "040" },
//   { location: "bitterfontein", code: "027" },
//   { location: "bizana", code: "039" },
//   { location: "bladgrond", code: "05442" },
//   { location: "blairbeth", code: "018" },
//   { location: "blikfontein", code: "053952" },
//   { location: "blinkpan", code: "013" },
//   { location: "bloedrivier", code: "034" },
//   { location: "bloemfontein", code: "051" },
//   { location: "bloemhof", code: "053" },
//   { location: "blomtuin", code: "045" },
//   { location: "bloubergstrand", code: "021" },
//   { location: "blouputs", code: "054" },
//   { location: "bochum", code: "015" },
//   { location: "bodenstein", code: "018" },
//   { location: "boegoeberg", code: "054" },
//   { location: "boesmanskop", code: "05542" },
//   { location: "boikhutso", code: "018" },
//   { location: "boknesstrand", code: "046" },
//   { location: "boksburg", code: "011" },
//   { location: "boksfontein", code: "049" },
//   { location: "boleu", code: "013" },
//   { location: "bolotwa", code: "047" },
//   { location: "bonnievale", code: "023" },
//   { location: "bosbokrand", code: "013" },
//   { location: "boshoek", code: "014" },
//   { location: "boshof", code: "053" },
//   { location: "boshof farm lines / plaaslyne", code: "053232" },
//   { location: "bosmansrus", code: "018" },
//   { location: "boston", code: "033" },
//   { location: "bothaville", code: "056" },
//   { location: "bothitong", code: "053" },
//   { location: "botrivier", code: "028" },
//   { location: "botshabelo", code: "051" },
//   { location: "boyne", code: "015" },
//   { location: "braamfontein", code: "011" },
//   { location: "braamfontein", code: "010" },
//   { location: "brackenfell", code: "021" },
//   { location: "braemar", code: "039" },
//   { location: "brakpan", code: "011" },
//   { location: "brandfort", code: "051" },
//   { location: "brandvlei", code: "054" },
//   { location: "brandvlei farm lines / plaaslyne", code: "054602" },
//   { location: "bray", code: "053" },
//   { location: "bray farm lines / plaaslyne", code: "0539372" },
//   { location: "bredasdorp", code: "028" },
//   { location: "bree river", code: "023" },
//   { location: "breyten", code: "017" },
//   { location: "brighton", code: "049" },
//   { location: "brits", code: "012" },
//   { location: "britstown", code: "053" },
//   { location: "britstown farm lines / plaaslyne", code: "0536712" },
//   { location: "broedersput", code: "053922" },
//   { location: "broederstroom", code: "012" },
//   { location: "bronkhorstspruit", code: "013" },
//   { location: "bryanston", code: "011" },
//   { location: "bryanston", code: "010" },
//   { location: "buffeljags river", code: "028" },
//   { location: "buffelsklip", code: "044" },
//   { location: "buhrmansdrif", code: "018" },
//   { location: "bulembu", code: "040" },
//   { location: "bulge river", code: "014" },
//   { location: "bultfontein", code: "051" },
//   { location: "bulwer", code: "039" },
//   { location: "burgersdorp", code: "051" },
//   { location: "burgersfort", code: "013" },
//   { location: "buthi", code: "013" },
//   { location: "butterworth", code: "047" },
//   { location: "cala", code: "047" },
//   { location: "caledon", code: "028" },
//   { location: "calitzdorp", code: "044" },
//   { location: "calvinia", code: "027" },
//   { location: "campbell", code: "053" },
//   { location: "camperdown", code: "031" },
//   { location: "cape town", code: "021" },
//   { location: "carletonville", code: "018" },
//   { location: "carnarvon", code: "053" },
//   { location: "carnarvon farm lines / plaaslyne", code: "0533822" },
//   { location: "carolina", code: "017" },
//   { location: "cathcart", code: "045" },
//   { location: "cato ridge", code: "031" },
//   { location: "cedarville", code: "039" },
//   { location: "centane", code: "047" },
//   { location: "centurion", code: "012" },
//   { location: "ceres", code: "023" },
//   { location: "ceza", code: "035" },
//   { location: "chalumna", code: "043" },
//   { location: "champagne valley", code: "036" },
//   { location: "charl cilliers", code: "017" },
//   { location: "chrissiefontein", code: "016" },
//   { location: "chrissiesmeer", code: "017" },
//   { location: "christiana", code: "053" },
//   { location: "chuenespoort", code: "015" },
//   { location: "citrusdal", code: "022" },
//   { location: "clanwilliam", code: "027" },
//   { location: "clarens", code: "058" },
//   { location: "clarkebury", code: "047" },
//   { location: "clarkson", code: "042" },
//   { location: "clocolan", code: "051" },
//   { location: "coalville", code: "013" },
//   { location: "coetzersdam", code: "053" },
//   { location: "coetzersdam farm lines / plaaslyne", code: "053972" },
//   { location: "coffee bay", code: "047" },
//   { location: "cofimvaba", code: "047" },
//   { location: "coldoug", code: "013" },
//   { location: "colenso", code: "036" },
//   { location: "colesberg", code: "051" },
//   { location: "coligny", code: "018" },
//   { location: "cookhouse", code: "042" },
//   { location: "copperton", code: "053" },
//   { location: "cornelia", code: "058" },
//   { location: "coronation", code: "034" },
//   { location: "cradock", code: "048" },
//   { location: "cramond", code: "033" },
//   { location: "creighton", code: "039" },
//   { location: "crowthorne", code: "011" },
//   { location: "crysbestos", code: "017" },
//   { location: "cullinan", code: "012" },
//   { location: "cullinan ridge", code: "011" },
//   { location: "cullinan ridge", code: "010" },
//   { location: "daleside", code: "016" },
//   { location: "dalton", code: "033" },
//   { location: "danielskuil", code: "053" },
//   { location: "dannhauser", code: "034" },
//   { location: "darling", code: "022" },
//   { location: "darnall", code: "032" },
//   { location: "davel", code: "017" },
//   { location: "daveyton", code: "011" },
//   { location: "de aar", code: "053" },
//   { location: "de deur", code: "016" },
//   { location: "de doorns", code: "023" },
//   { location: "dejagersdrif", code: "034" },
//   { location: "de rust", code: "044" },
//   { location: "de wildt", code: "012" },
//   { location: "dealesville", code: "051" },
//   { location: "dealesville farm lines / plaaslyne", code: "05292" },
//   { location: "delareyville", code: "053" },
//   { location: "delmas", code: "013" },
//   { location: "delportshoop", code: "053" },
//   { location: "dendron", code: "015" },
//   { location: "deneysville", code: "016" },
//   { location: "dennilton", code: "013" },
//   { location: "derby", code: "014" },
//   { location: "despatch", code: "041" },
//   { location: "devon", code: "017" },
//   { location: "de wagensdrift", code: "012" },
//   { location: "dewetsdorp", code: "051" },
//   { location: "dewetsdorp farm lines / plaaslyne", code: "052112" },
//   { location: "dibeng", code: "053" },
//   { location: "dienje", code: "013" },
//   { location: "diepdal", code: "017" },
//   { location: "dikgale", code: "015" },
//   { location: "dilokong", code: "015" },
//   { location: "dimbaza", code: "040" },
//   { location: "dinokana", code: "018" },
//   { location: "disaneng", code: "018" },
//   { location: "dominionville", code: "018" },
//   { location: "donkerpoort", code: "051782" },
//   { location: "donnybrook", code: "039" },
//   { location: "dordrecht", code: "045" },
//   { location: "doring bay", code: "027" },
//   { location: "doringkop", code: "032" },
//   { location: "douglas", code: "053" },
//   { location: "douglas mine", code: "013" },
//   { location: "douglas village", code: "013" },
//   { location: "driekop", code: "013" },
//   { location: "dudfield", code: "018" },
//   { location: "duiwelskloof", code: "015" },
//   { location: "dullstroom", code: "013" },
//   { location: "dundee", code: "034" },
//   { location: "dundonald", code: "017" },
//   { location: "dunnottar", code: "011" },
//   { location: "durban", code: "031" },
//   { location: "durnacol", code: "034" },
//   { location: "dutywa", code: "047" },
//   { location: "dwaalboom", code: "014" },
//   { location: "dwarskersbos", code: "022" },
//   { location: "dwars river", code: "015" },
//   { location: "dysselsdorp", code: "044" },
//   { location: "dzanani", code: "015" },
//   { location: "east london", code: "043" },
//   { location: "ebilanyoni", code: "034" },
//   { location: "edenburg", code: "051" },
//   { location: "edenburg farm lines / plaaslyne", code: "051742" },
//   { location: "edenvale", code: "011" },
//   { location: "edenvale", code: "010" },
//   { location: "edenville (fs/vs)", code: "056" },
//   { location: "edenway", code: "011" },
//   { location: "edgley", code: "031" },
//   { location: "edna", code: "015" },
//   { location: "eendekuil", code: "022" },
//   { location: "eerste river", code: "021" },
//   { location: "eight bells", code: "044" },
//   { location: "ekhandizwe", code: "013" },
//   { location: "ekulendeni", code: "017" },
//   { location: "ekuseni", code: "034" },
//   { location: "ekuvukeni", code: "034" },
//   { location: "elands bay", code: "022" },
//   { location: "elandsfontein", code: "013" },
//   { location: "elandslaagte", code: "036" },
//   { location: "elandsrand", code: "018" },
//   { location: "elim hospital", code: "015" },
//   { location: "elliot", code: "045" },
//   { location: "elliotdale", code: "047" },
//   { location: "ellisras", code: "014" },
//   { location: "elukwatini", code: "017" },
//   { location: "emakhazeni", code: "013" },
//   { location: "emalahleni", code: "013" },
//   { location: "emgwenya", code: "013" },
//   { location: "emjejane", code: "013" },
//   { location: "emondlo", code: "034" },
//   { location: "empangeni", code: "035" },
//   { location: "empanjati", code: "039" },
//   { location: "empumalanga", code: "013" },
//   { location: "endicott", code: "011" },
//   { location: "engcobo", code: "047" },
//   { location: "entokozweni", code: "013" },
//   { location: "erand", code: "011" },
//   { location: "erand", code: "010" },
//   { location: "erica", code: "021" },
//   { location: "ermelo", code: "017" },
//   { location: "eshowe", code: "035" },
//   { location: "estcourt", code: "036" },
//   { location: "eston", code: "031" },
//   { location: "etikhulungwane", code: "017" },
//   { location: "evander", code: "017" },
//   { location: "excelsior", code: "051" },
//   { location: "ezibeleni", code: "047" },
//   { location: "faure", code: "021" },
//   { location: "fauresmith", code: "051" },
//   { location: "fauresmith farm lines / plaaslyne", code: "051722" },
//   { location: "fawn leas", code: "033" },
//   { location: "ficksburg", code: "051" },
//   { location: "firgrove", code: "021" },
//   { location: "fish river mouth", code: "040" },
//   { location: "flagstaff", code: "039" },
//   { location: "florida", code: "011" },
//   { location: "florida", code: "010" },
//   { location: "fochville", code: "018" },
//   { location: "fort beaufort", code: "046" },
//   { location: "fouriesburg", code: "058" },
//   { location: "frankfort", code: "058" },
//   { location: "franklin", code: "039" },
//   { location: "franschhoek", code: "021" },
//   { location: "fraserburg", code: "023" },
//   { location: "fraserburg farm lines / plaaslyne", code: "02072" },
//   { location: "ga-nala", code: "017" },
//   { location: "ga-rankuwa", code: "012" },
//   { location: "gakgapane", code: "015" },
//   { location: "gamalakhe", code: "039" },
//   { location: "gamarota", code: "013" },
//   { location: "gansbaai", code: "028" },
//   { location: "ganyesa", code: "053" },
//   { location: "ganyesa farm lines / plaaslyne", code: "0539982" },
//   { location: "garagams", code: "027" },
//   { location: "gariepdam", code: "051" },
//   { location: "garies", code: "027" },
//   { location: "gedeonsfontein", code: "0533912" },
//   { location: "geelputs", code: "054902" },
//   { location: "gelegenfontein", code: "048" },
//   { location: "gelukspruit", code: "054" },
//   { location: "gelukspruit farm lines / plaaslyne", code: "054902" },
//   { location: "gemsbokpark", code: "054" },
//   { location: "genadendal", code: "028" },
//   { location: "george", code: "044" },
//   { location: "gerdau", code: "018" },
//   { location: "germiston", code: "011" },
//   { location: "geysdorp", code: "053" },
//   { location: "gezubuso", code: "033" },
//   { location: "gingindlovu", code: "035" },
//   { location: "giyani", code: "015" },
//   { location: "glen", code: "051" },
//   { location: "glen cowie", code: "013" },
//   { location: "glenharvie", code: "011" },
//   { location: "glenred", code: "053" },
//   { location: "glencoe", code: "034" },
//   { location: "glenmill", code: "032" },
//   { location: "gluckstadt", code: "034" },
//   { location: "goedemoed", code: "051" },
//   { location: "golden gate", code: "058" },
//   { location: "golela", code: "034" },
//   { location: "gompies", code: "015" },
//   { location: "gonubie", code: "043" },
//   { location: "gordon's bay", code: "021" },
//   { location: "gouda", code: "023" },
//   { location: "gouritsmond", code: "028" },
//   { location: "graaff-reinet", code: "049" },
//   { location: "graafwater", code: "027" },
//   { location: "grabouw", code: "021" },
//   { location: "grahamstown", code: "046" },
//   { location: "granaatboskolk", code: "054" },
//   { location: "granaatboskolk farm lines/plaaslyne", code: "054602" },
//   { location: "graskop", code: "013" },
//   { location: "gravelotte", code: "015" },
//   { location: "greylingstad", code: "017" },
//   { location: "greyton (wc/wk)", code: "028" },
//   { location: "greytown (kzn)", code: "033" },
//   { location: "griekwastad", code: "053" },
//   { location: "griekwastad farm lines / plaaslyne", code: "05962" },
//   { location: "groblersdal", code: "013" },
//   { location: "groblershoop", code: "054" },
//   { location: "groblershoop farm lines / plaaslyne", code: "05472" },
//   { location: "groot-brakrivier", code: "044" },
//   { location: "groot-marico", code: "014" },
//   { location: "groot-marico farm lines / plaaslyne", code: "014252" },
//   { location: "grootdrink", code: "054" },
//   { location: "grootdrink farm lines / plaaslyne", code: "0547412" },
//   { location: "grootvlei", code: "017" },
//   { location: "groutville", code: "032" },
//   { location: "haarlem", code: "044" },
//   { location: "haasvlakte", code: "028" },
//   { location: "hackney", code: "040" },
//   { location: "haenertsburg", code: "015" },
//   { location: "hagesdam", code: "051" },
//   { location: "halfway house", code: "011" },
//   { location: "halfway house", code: "010" },
//   { location: "hamburg", code: "040" },
//   { location: "hammanskraal", code: "012" },
//   { location: "hankey", code: "042" },
//   { location: "hanover", code: "053" },
//   { location: "hanover farm lines / plaaslyne", code: "053642" },
//   { location: "harburg", code: "033" },
//   { location: "harding", code: "039" },
//   { location: "harrismith", code: "058" },
//   { location: "hartbeesfontein", code: "018" },
//   { location: "hartbeespoort", code: "012" },
//   { location: "hartenbos", code: "044" },
//   { location: "hartsvallei", code: "053" },
//   { location: "hartswater", code: "053" },
//   { location: "hawston", code: "028" },
//   { location: "hazyview", code: "013" },
//   { location: "healdtown", code: "046" },
//   { location: "hectorspruit", code: "013" },
//   { location: "heidelberg (g)", code: "016" },
//   { location: "heidelberg (wc/wk)", code: "028" },
//   { location: "heilbron", code: "058" },
//   { location: "hekpoort", code: "014" },
//   { location: "helpmekaar", code: "034" },
//   { location: "hendrina", code: "013" },
//   { location: "henley on klip", code: "016" },
//   { location: "hennenman", code: "057" },
//   { location: "herbertsdale", code: "044" },
//   { location: "hermannsburg", code: "033" },
//   { location: "hermanus", code: "028" },
//   { location: "herold", code: "044" },
//   { location: "herschel", code: "05552" },
//   { location: "hertzogville", code: "053" },
//   { location: "heuningvlei", code: "05492" },
//   { location: "hibberdene", code: "039" },
//   { location: "highflats", code: "039" },
//   { location: "hillbrow", code: "011" },
//   { location: "hillbrow", code: "010" },
//   { location: "himeville", code: "033" },
//   { location: "hlabisa", code: "035" },
//   { location: "hlobane", code: "034" },
//   { location: "hluhluwe", code: "035" },
//   { location: "hluvukani", code: "013" },
//   { location: "hobhouse", code: "051" },
//   { location: "hobhouse farm lines / plaaslyne", code: "051982" },
//   { location: "hoedspruit", code: "015" },
//   { location: "hofmeyr", code: "048" },
//   { location: "hogsback", code: "045" },
//   { location: "hondeklip bay", code: "027" },
//   { location: "hoopstad", code: "053" },
//   { location: "hopefield", code: "022" },
//   { location: "hopetown", code: "053" },
//   { location: "hotazel", code: "053" },
//   { location: "houghsplaas", code: "053" },
//   { location: "houghsplaas plaaslyne/farm lines", code: "0533912" },
//   { location: "howick", code: "033" },
//   { location: "hugorus", code: "023" },
//   { location: "humansdorp", code: "042" },
//   { location: "hutchinson", code: "053612" },
//   { location: "ida", code: "045" },
//   { location: "idutywa", code: "047" },
//   { location: "ifafa beach", code: "039" },
//   { location: "iketlo", code: "011" },
//   { location: "ilinge", code: "047" },
//   { location: "ilitha", code: "040" },
//   { location: "imbongozi", code: "013" },
//   { location: "impendle", code: "033" },
//   { location: "indermark", code: "015" },
//   { location: "industriqwa", code: "058" },
//   { location: "indwe", code: "045" },
//   { location: "ingogo", code: "034" },
//   { location: "ingwavuma", code: "035" },
//   { location: "inverness", code: "034" },
//   { location: "inxu drift", code: "047" },
//   { location: "isando", code: "011" },
//   { location: "isando", code: "010" },
//   { location: "isithebe", code: "032" },
//   { location: "iswepe", code: "017" },
//   { location: "itsoseng", code: "018" },
//   { location: "ixopo", code: "039" },
//   { location: "izingolweni", code: "039" },
//   { location: "izotsha", code: "039" },
//   { location: "jacobsdal", code: "053" },
//   { location: "jacobsdal farm lines / plaaslyne", code: "053212" },
//   { location: "jagersfontein", code: "051" },
//   { location: "jagersfontein farm lines / plaaslyne", code: "051732" },
//   { location: "jagerskraal", code: "023" },
//   { location: "jagersrust", code: "036" },
//   { location: "jamestown", code: "051" },
//   { location: "jan kempdorp", code: "053" },
//   { location: "jane furse hospital", code: "013" },
//   { location: "jansenville", code: "049" },
//   { location: "jeffreys bay", code: "042" },
//   { location: "jericho", code: "012" },
//   { location: "jerusalem", code: "013" },
//   { location: "johannesburg", code: "011" },
//   { location: "johannesburg", code: "010" },
//   { location: "johannesburg city", code: "011" },
//   { location: "johannesburg city", code: "010" },
//   { location: "jongensfontein", code: "028" },
//   { location: "joostepan", code: "054902" },
//   { location: "joubertina", code: "042" },
//   { location: "jozini", code: "035" },
//   { location: "juno", code: "015" },
//   { location: "kaapmuiden", code: "013" },
//   { location: "kaapstad", code: "021" },
//   { location: "kabokweni", code: "013" },
//   { location: "kakamas", code: "054" },
//   { location: "kalafi", code: "014" },
//   { location: "kamaspan", code: "02762" },
//   { location: "kameel", code: "053" },
//   { location: "kameel farm lines / plaaslyne", code: "053982" },
//   { location: "kameelpoort", code: "013" },
//   { location: "kamieskroon", code: "027" },
//   { location: "kandaspunt", code: "034" },
//   { location: "kanoneiland", code: "054" },
//   { location: "kanyamazane", code: "013" },
//   { location: "karatara", code: "044" },
//   { location: "kareedouw", code: "042" },
//   { location: "karos", code: "054" },
//   { location: "kathu", code: "053" },
//   { location: "katkop", code: "047" },
//   { location: "kayakulu", code: "014" },
//   { location: "keate's drift", code: "033" },
//   { location: "kei mouth", code: "043" },
//   { location: "kei road", code: "043" },
//   { location: "keimoes", code: "054" },
//   { location: "keiskammahoek", code: "040" },
//   { location: "kelvin", code: "011" },
//   { location: "kelvin", code: "010" },
//   { location: "kempton park", code: "011" },
//   { location: "kempton park", code: "010" },
//   { location: "kendal", code: "013" },
//   { location: "kenhardt", code: "054" },
//   { location: "kenhardt farm lines / plaaslyne", code: "05462" },
//   { location: "kentani", code: "047" },
//   { location: "kenton on sea", code: "046" },
//   { location: "kestell", code: "058" },
//   { location: "kestell farm lines / plaaslyne", code: "058652" },
//   { location: "kidd's beach", code: "043" },
//   { location: "kimberley", code: "010" },
//   { location: "king william's town", code: "043" },
//   { location: "kinross", code: "017" },
//   { location: "kirkwood", code: "042" },
//   { location: "klaarfontein", code: "045" },
//   { location: "klawer", code: "027" },
//   { location: "klein-mier", code: "054902" },
//   { location: "kleinbegin", code: "05472" },
//   { location: "kleinmonde", code: "046" },
//   { location: "kleinmond", code: "028" },
//   { location: "kleinsee", code: "027" },
//   { location: "klerksdorp", code: "018" },
//   { location: "klipheuwel", code: "021" },
//   { location: "klipplaat", code: "049" },
//   { location: "kliprand", code: "027" },
//   { location: "kloof", code: "031" },
//   { location: "knysna", code: "044" },
//   { location: "koedoeskop", code: "014" },
//   { location: "koegasbrug", code: "05482" },
//   { location: "koeipan", code: "059512" },
//   { location: "koelenhof", code: "021" },
//   { location: "koffiefontein", code: "053" },
//   { location: "koffiefontein farm lines / plaaslyne", code: "053242" },
//   { location: "kokstad", code: "039" },
//   { location: "koloti", code: "015" },
//   { location: "komaggas", code: "027" },
//   { location: "komatipoort", code: "013" },
//   { location: "komga", code: "043" },
//   { location: "komkans", code: "027" },
//   { location: "koopmansfontein", code: "053862" },
//   { location: "koppies", code: "056" },
//   { location: "koster", code: "014" },
//   { location: "koue bokkeveld", code: "023" },
//   { location: "koupan", code: "054" },
//   { location: "koupan farm lines/plaaslyne", code: "054902" },
//   { location: "kraaifontein", code: "021" },
//   { location: "kraaipan", code: "018" },
//   { location: "kragbron", code: "016" },
//   { location: "kranskop", code: "033" },
//   { location: "kriel", code: "017" },
//   { location: "krom river (nw)", code: "014" },
//   { location: "krom river (nc/nk)", code: "053612" },
//   { location: "kroonstad", code: "056" },
//   { location: "krugersdorp", code: "017" },
//   { location: "krugersdorp", code: "010" },
//   { location: "kunana", code: "018" },
//   { location: "kunana farm lines / plaaslyne", code: "014092" },
//   { location: "kuruman", code: "053" },
//   { location: "kwadukuza", code: "032" },
//   { location: "kwaguquka", code: "040" },
//   { location: "kwalugedlane", code: "013" },
//   { location: "kwamashu", code: "031" },
//   { location: "kwambonambi", code: "035" },
//   { location: "kwamhlanga", code: "013" },
//   { location: "kwamhluswa", code: "013" },
//   { location: "kwamsane", code: "035" },
//   { location: "kwandwayana", code: "040" },
//   { location: "kwangwanase", code: "035" },
//   { location: "kwathema", code: "011" },
//   { location: "kwaxuma", code: "011" },
//   { location: "kwazamokuhle", code: "013" },
//   { location: "ladismith (wc/wk)", code: "028" },
//   { location: "lady frere", code: "047" },
//   { location: "lady grey", code: "051" },
//   { location: "ladynavbar-brand", code: "051" },
//   { location: "ladysmith (kzn)", code: "036" },
//   { location: "laersdrif", code: "013" },
//   { location: "laingsburg", code: "023" },
//   { location: "lambert's bay", code: "027" },
//   { location: "kwazamokuhle", code: "013" },
//   { location: "kwazamokuhle", code: "013" },
//   { location: "langebaan", code: "022" },
//   { location: "langebaanroad", code: "022" },
//   { location: "langeni", code: "047" },
//   { location: "langklip", code: "054902" },
//   { location: "langkrans", code: "034" },
//   { location: "laparisa", code: "013" },
//   { location: "kwazamokuhle", code: "013" },
//   { location: "kwazamokuhle", code: "015" },
//   { location: "lebowakgomo", code: "015" },
//   { location: "leeu-gamka", code: "023" },
//   { location: "leeu-gamka farm lines / plaaslyne", code: "02082" },
//   { location: "leeudoringstad", code: "018" },
//   { location: "leeupoort", code: "014" },
//   { location: "leipoldtville", code: "027" },
//   { location: "lemkins", code: "015" },
//   { location: "lenasia", code: "011" },
//   { location: "leniesdeel", code: "053972" },
//   { location: "lenyenye", code: "015" },
//   { location: "leopard creek", code: "013" },
//   { location: "lephalale", code: "014" },
//   { location: "lerato", code: "018" },
//   { location: "lesedi village", code: "013" },
//   { location: "leslie", code: "017" },
//   { location: "lethabong", code: "018" },
//   { location: "letlhabile", code: "012" },
//   { location: "letsitele", code: "015" },
//   { location: "letskraal", code: "049" },
//   { location: "levubu", code: "015" },
//   { location: "libode", code: "047" },
//   { location: "lichtenburg", code: "018" },
//   { location: "lidgetton", code: "033" },
//   { location: "limburg", code: "015" },
//   { location: "lime acres", code: "053" },
//   { location: "lindley", code: "058" },
//   { location: "lindley farm lines / plaaslyne", code: "05612" },
//   { location: "lochvaal", code: "016" },
//   { location: "loerie", code: "042" },
//   { location: "loeriesfontein", code: "027" },
//   { location: "loeriesfontein farm lines / plaaslyne", code: "02762" },
//   { location: "logagane", code: "018" },
//   { location: "lohatlha", code: "053" },
//   { location: "longlands", code: "05352" },
//   { location: "lonsdale", code: "015" },
//   { location: "loogkolk", code: "05462" },
//   { location: "losperfontein", code: "012" },
//   { location: "losperplaas", code: "02762" },
//   { location: "lothair", code: "017" },
//   { location: "lotlhakane", code: "018" },
//   { location: "louis trichardt", code: "015" },
//   { location: "louisvale", code: "054" },
//   { location: "low's creek", code: "013" },
//   { location: "louwsburg", code: "034" },
//   { location: "loxton", code: "053" },
//   { location: "loxton farm lines / plaaslyne", code: "0533812" },
//   { location: "luckhoff", code: "053" },
//   { location: "luckhoff farm lines / plaaslyne", code: "053272" },
//   { location: "lulekani", code: "015" },
//   { location: "lusikisiki", code: "039" },
//   { location: "lutzputs", code: "054902" },
//   { location: "lutzville", code: "027" },
//   { location: "lwamondo", code: "015" },
//   { location: "lydenburg", code: "013" },
//   { location: "lykso", code: "053952" },
//   { location: "lynedoch", code: "021" },
//   { location: "mabeskraal", code: "014" },
//   { location: "mabopane", code: "012" },
//   { location: "machadodorp", code: "013" },
//   { location: "macleantown", code: "043" },
//   { location: "maclear", code: "045" },
//   { location: "madibogo", code: "018" },
//   { location: "madikwe", code: "014" },
//   { location: "mafatsana", code: "016" },
//   { location: "mafikeng", code: "018" },
//   { location: "magaliesburg", code: "014" },
//   { location: "magelembe", code: "013" },
//   { location: "magudu", code: "034" },
//   { location: "mahlabatini", code: "035" },
//   { location: "mahwelereng", code: "015" },
//   { location: "maja", code: "015" },
//   { location: "makapanstad", code: "012" },
//   { location: "makgobistad", code: "018" },
//   { location: "makhado", code: "015" },
//   { location: "makonde", code: "015" },
//   { location: "makwassie", code: "018" },
//   { location: "malalane", code: "013" },
//   { location: "malamulele", code: "015" },
//   { location: "malelane", code: "013" },
//   { location: "malmesbury", code: "022" },
//   { location: "maluti", code: "039" },
//   { location: "mamelodi east/-oos", code: "012" },
//   { location: "mamelodi west/-wes", code: "012" },
//   { location: "mamuza", code: "014" },
//   { location: "mandini", code: "032" },
//   { location: "manthestad", code: "053992" },
//   { location: "manyeding", code: "053" },
//   { location: "mapela", code: "015" },
//   { location: "mapumulo", code: "032" },
//   { location: "marapyane", code: "012" },
//   { location: "marble hall", code: "013" },
//   { location: "marchand", code: "054" },
//   { location: "mareetsane", code: "018" },
//   { location: "margate", code: "039" },
//   { location: "marikana", code: "014" },
//   { location: "marishane", code: "013" },
//   { location: "marken", code: "014" },
//   { location: "marobeng", code: "051" },
//   { location: "marquard", code: "051" },
//   { location: "marydale", code: "054" },
//   { location: "marydale farm lines / plaaslyne", code: "05482" },
//   { location: "mashashane", code: "015" },
//   { location: "mashau", code: "015" },
//   { location: "mashishing", code: "013" },
//   { location: "masia", code: "015" },
//   { location: "masisi", code: "015" },
//   { location: "masoheng", code: "016" },
//   { location: "matatiele", code: "039" },
//   { location: "matjhirini", code: "013" },
//   { location: "matjiesfontein", code: "023" },
//   { location: "matsulu", code: "013" },
//   { location: "mbazwana", code: "035" },
//   { location: "mbibane", code: "013" },
//   { location: "mbombela", code: "013" },
//   { location: "mcgregor", code: "023" },
//   { location: "mdantsane", code: "043" },
//   { location: "mecklenburg", code: "045" },
//   { location: "meerlus", code: "013" },
//   { location: "melkbosstrand", code: "021" },
//   { location: "melmoth", code: "035" },
//   { location: "memel", code: "058" },
//   { location: "merriespan", code: "054" },
//   { location: "merriespan farmlines/plaaslyne", code: "054902" },
//   { location: "merriman", code: "0536912" },
//   { location: "merweville", code: "023" },
//   { location: "merweville farm lines / plaaslyne", code: "02062" },
//   { location: "messina", code: "015" },
//   { location: "meyerton", code: "016" },
//   { location: "middelburg (ec/ok)", code: "049" },
//   { location: "middelburg (m)", code: "013" },
//   { location: "middledrift", code: "040" },
//   { location: "mier", code: "054" },
//   { location: "mier farm lines / plaaslyne", code: "0545312" },
//   { location: "miga", code: "018" },
//   { location: "migdol", code: "053" },
//   { location: "miller", code: "044" },
//   { location: "minga", code: "047" },
//   { location: "misgund", code: "042" },
//   { location: "mispunt", code: "049" },
//   { location: "mitford", code: "040" },
//   { location: "mkhuhlu", code: "013" },
//   { location: "mkuze", code: "035" },
//   { location: "mmabatho", code: "018" },
//   { location: "modimola", code: "018" },
//   { location: "modimolle", code: "014" },
//   { location: "modjadji", code: "015" },
//   { location: "modjadjiskloof", code: "015" },
//   { location: "moedwil", code: "014" },
//   { location: "moetladimo", code: "015" },
//   { location: "moganyaka", code: "013" },
//   { location: "mogodumo", code: "015" },
//   { location: "mogwadi", code: "015" },
//   { location: "mogwase", code: "014" },
//   { location: "mokgareng", code: "053992" },
//   { location: "mokgathla", code: "014" },
//   { location: "mokopane", code: "015" },
//   { location: "molatedi", code: "014" },
//   { location: "molototsi", code: "015" },
//   { location: "molsvlei", code: "027" },
//   { location: "molteno", code: "045" },
//   { location: "monnakato", code: "014" },
//   { location: "mononono", code: "014" },
//   { location: "montagu", code: "023" },
//   { location: "mooinooi", code: "014" },
//   { location: "mooiplaas", code: "043" },
//   { location: "mooi river", code: "033" },
//   { location: "mooketsi", code: "015" },
//   { location: "mookgophong", code: "014" },
//   { location: "moolman", code: "017" },
//   { location: "moorreesburg", code: "022" },
//   { location: "morebeng", code: "015" },
//   { location: "morgenzon", code: "017" },
//   { location: "morgenzon farm lines / plaaslyne", code: "0172182" },
//   { location: "morokweng", code: "053" },
//   { location: "mortimer", code: "048" },
//   { location: "mossel bay", code: "044" },
//   { location: "motetema", code: "013" },
//   { location: "mothibistad", code: "053" },
//   { location: "mothutlung", code: "012" },
//   { location: "motswedi", code: "018" },
//   { location: "mount ayliff", code: "039" },
//   { location: "mount fletcher", code: "039" },
//   { location: "mount frere", code: "039" },
//   { location: "mphahlele", code: "015" },
//   { location: "mphephu", code: "015" },
//   { location: "mpophomeni", code: "033" },
//   { location: "mpudulle", code: "013" },
//   { location: "mpuluzi", code: "017" },
//   { location: "mqanduli", code: "047" },
//   { location: "msongelwa", code: "013" },
//   { location: "mthatha", code: "047" },
//   { location: "mtubatuba", code: "035" },
//   { location: "mtunzini", code: "035" },
//   { location: "mtwalume", code: "039" },
//   { location: "muden", code: "033" },
//   { location: "muldersvlei", code: "021" },
//   { location: "mulima", code: "015" },
//   { location: "munshedzi", code: "015" },
//   { location: "murraysburg", code: "049" },
//   { location: "musina", code: "015" },
//   { location: "muswodi", code: "015" },
//   { location: "mutale", code: "015" },
//   { location: "muthathi", code: "015" },
//   { location: "mzamba", code: "039" },
//   { location: "naboomspruit", code: "014" },
//   { location: "naledi", code: "013" },
//   { location: "namakgale", code: "015" },
//   { location: "namies", code: "05492" },
//   { location: "napier", code: "028" },
//   { location: "napkei", code: "028" },
//   { location: "nature's valley", code: "044" },
//   { location: "ncora", code: "047" },
//   { location: "ncorha", code: "047" },
//   { location: "ndwedwe", code: "032" },
//   { location: "nelspoort", code: "023" },
//   { location: "nelspruit", code: "013" },
//   { location: "neverset", code: "023" },
//   { location: "new hanover", code: "033" },
//   { location: "newcastle", code: "034" },
//   { location: "newlands", code: "011" },
//   { location: "newlands", code: "010" },
//   { location: "ngcobo", code: "047" },
//   { location: "ngodwana", code: "013" },
//   { location: "ngqeleni", code: "047" },
//   { location: "ngudwini", code: "035" },
//   { location: "nhlazatshe", code: "034" },
//   { location: "niekerkshoop", code: "053" },
//   { location: "nietverdiend", code: "018" },
//   { location: "nietverdiend farm lines/plaaslyne", code: "0183672" },
//   { location: "nieu-bethesda", code: "049" },
//   { location: "nieuwoudtville", code: "027" },
//   { location: "nigel", code: "011" },
//   { location: "nkandla", code: "035" },
//   { location: "nkowakowa", code: "015" },
//   { location: "nkwalini", code: "035" },
//   { location: "noenieput", code: "054" },
//   { location: "noenieput farm lines / plaaslyne", code: "054902" },
//   { location: "noll", code: "044" },
//   { location: "nongoma", code: "035" },
//   { location: "noordkaap", code: "013" },
//   { location: "nigel", code: "011" },
//   { location: "nigel", code: "011" },
//   { location: "normandien", code: "034" },
//   { location: "northam", code: "014" },
//   { location: "norvalspont", code: "051" },
//   { location: "nottingham road", code: "033" },
//   { location: "noupoort", code: "049" },
//   { location: "nqabeni", code: "039" },
//   { location: "nqamakwe", code: "047" },
//   { location: "nqutu", code: "034" },
//   { location: "nsikazi", code: "013" },
//   { location: "ntabankulu", code: "039" },
//   { location: "ntwenka", code: "047" },
//   { location: "nucam", code: "017" },
//   { location: "nuwerus", code: "027" },
//   { location: "nwamanunga", code: "015" },
//   { location: "nwamitwa", code: "015" },
//   { location: "nylstroom", code: "014" },
//   { location: "nyoni", code: "032" },
//   { location: "nzhelele", code: "015" },
//   { location: "odendaalsrus", code: "057" },
//   { location: "oester bay", code: "042" },
//   { location: "ogies", code: "013" },
//   { location: "ohrigstad", code: "013" },
//   { location: "olifantsfontein", code: "011" },
//   { location: "olifantshoek", code: "053" },
//   { location: "olifantshoek farm lines / plaaslyne", code: "059512" },
//   { location: "olivedale", code: "011" },
//   { location: "olivedale", code: "010" },
//   { location: "onderstedorings", code: "054602" },
//   { location: "onderstepoort", code: "054" },
//   { location: "onrusrivier", code: "028" },
//   { location: "onseepkans", code: "054" },
//   { location: "oos-londen", code: "043" },
//   { location: "oppermans", code: "053" },
//   { location: "oppermans farm lines / plaaslyne", code: "0532092" },
//   { location: "opstaan", code: "054902" },
//   { location: "orania", code: "053" },
//   { location: "oranjeville", code: "016" },
//   { location: "orchard", code: "023" },
//   { location: "orkney", code: "018" },
//   { location: "oshoek", code: "017" },
//   { location: "osizweni", code: "034" },
//   { location: "ottosdal", code: "018" },
//   { location: "ottoshoop", code: "018" },
//   { location: "oubos", code: "042" },
//   { location: "ouboskolk", code: "054602" },
//   { location: "oudtshoorn", code: "044" },
//   { location: "ozwatini", code: "032" },
//   { location: "paarl", code: "021" },
//   { location: "pacaltsdorp", code: "044" },
//   { location: "paddock", code: "039" },
//   { location: "pampierstad", code: "053" },
//   { location: "pampoenpoort", code: "053612" },
//   { location: "panorama", code: "011" },
//   { location: "panorama", code: "010" },
//   { location: "parow", code: "021" },
//   { location: "parys", code: "056" },
//   { location: "patensie", code: "042" },
//   { location: "paternoster", code: "022" },
//   { location: "paterson", code: "042" },
//   { location: "paul roux", code: "058" },
//   { location: "paulpietersburg", code: "021" },
//   { location: "paulusweg", code: "015" },
//   { location: "pearly beach", code: "028" },
//   { location: "pearston", code: "042" },
//   { location: "peddie", code: "040" },
//   { location: "pella", code: "054" },
//   { location: "pella farm lines / plaaslyne", code: "0549712" },
//   { location: "perdeberg", code: "053" },
//   { location: "perdekop", code: "017" },
//   { location: "petit", code: "011" },
//   { location: "petrus steyn", code: "058" },
//   { location: "petrusburg", code: "053" },
//   { location: "petrusburg farm lines / plaaslyne", code: "05282" },
//   { location: "petrusville", code: "053" },
//   { location: "petrusville farm lines / plaaslyne", code: "0536612" },
//   { location: "phalaborwa", code: "015" },
//   { location: "philadelphia", code: "021" },
//   { location: "philippolis", code: "051" },
//   { location: "phillipstown", code: "053" },
//   { location: "phillipstown farm lines / plaaslyne", code: "053652" },
//   { location: "phokeng", code: "014" },
//   { location: "phokwane", code: "013" },
//   { location: "phola", code: "013" },
//   { location: "photsaneng", code: "014" },
//   { location: "phuthaditjhaba", code: "058" },
//   { location: "pienaarsrivier", code: "012" },
//   { location: "piet plessis", code: "053" },
//   { location: "piet plessis farm lines / plaaslyne", code: "0539842" },
//   { location: "piet retief", code: "017" },
//   { location: "pietermaritzburg", code: "033" },
//   { location: "pietersburg", code: "015" },
//   { location: "piketberg", code: "022" },
//   { location: "pilanesberg", code: "014" },
//   { location: "pilgrim's rest", code: "013" },
//   { location: "pinetown", code: "031" },
//   { location: "plettenbergbaai", code: "044" },
//   { location: "plooysburg", code: "053" },
//   { location: "plooysburg farm lines / plaaslyne", code: "0535892" },
//   { location: "pofadder", code: "054" },
//   { location: "pofadder farm lines / plaaslyne", code: "05492" },
//   { location: "politsi", code: "015" },
//   { location: "polokwane", code: "015" },
//   { location: "pomeroy", code: "034" },
//   { location: "pomfret", code: "053" },
//   { location: "pomona", code: "011" },
//   { location: "pongola", code: "034" },
//   { location: "port alfred", code: "046" },
//   { location: "port edward", code: "039" },
//   { location: "port elizabeth", code: "041" },
//   { location: "port nolloth", code: "027" },
//   { location: "port shepstone", code: "039" },
//   { location: "port st johns", code: "047" },
//   { location: "porterville", code: "022" },
//   { location: "postmasburg", code: "053" },
//   { location: "potchefstroom", code: "018" },
//   { location: "potgietersrus", code: "015" },
//   { location: "pretoria", code: "012" },
//   { location: "prieska", code: "053" },
//   { location: "prince albert", code: "023" },
//   { location: "prince albert road", code: "023" },
//   { location: "prince albert road farm lines / plaaslyne", code: "02082" },
//   { location: "prince alfred hamlet", code: "023" },
//   { location: "pringle bay", code: "028" },
//   { location: "priors", code: "051782" },
//   { location: "protem", code: "028" },
//   { location: "pudimoe", code: "053" },
//   { location: "pullen's hope", code: "013" },
//   { location: "putsonderwater", code: "054" },
//   { location: "putsonderwater farm lines / plaaslyne", code: "05472" },
//   { location: "qudeni", code: "035" },
//   { location: "queenstown", code: "045" },
//   { location: "qumbu", code: "047" },
//   { location: "raap en skraap", code: "054" },
//   { location: "radithuso", code: "018" },
//   { location: "radium", code: "014" },
//   { location: "ramokgopa", code: "015" },
//   { location: "ramokokastad", code: "014" },
//   { location: "ramsgate", code: "039" },
//   { location: "randburg", code: "011" },
//   { location: "randfontein", code: "011" },
//   { location: "rawsonville", code: "023" },
//   { location: "rebone", code: "015" },
//   { location: "reddersburg", code: "051" },
//   { location: "reddersburg farm lines / plaaslyne", code: "052122" },
//   { location: "redelinghuys", code: "022" },
//   { location: "reitz", code: "058" },
//   { location: "reivilo", code: "053" },
//   { location: "reivilo farm lines / plaaslyne", code: "053952" },
//   { location: "residensia", code: "016" },
//   { location: "rhenosterkraal", code: "014" },
//   { location: "rhodes", code: "045" },
//   { location: "richards bay", code: "035" },
//   { location: "richmond (nc/nk)", code: "053" },
//   { location: "richmond (nc/nk) farm lines / plaaslyne", code: "0536912" },
//   { location: "richmond (kzn)", code: "033" },
//   { location: "riebeek-kasteel", code: "022" },
//   { location: "riebeek west", code: "022" },
//   { location: "rietbron", code: "014" },
//   { location: "rietkuil", code: "013" },
//   { location: "rietpoort", code: "048" },
//   { location: "rietspruit", code: "013" },
//   { location: "rietvlei", code: "039" },
//   { location: "ritchie", code: "053" },
//   { location: "riversdale", code: "028" },
//   { location: "riviersonderend", code: "028" },
//   { location: "robertson", code: "023" },
//   { location: "rocky ridge", code: "041" },
//   { location: "roedtan", code: "015" },
//   { location: "roodepoort", code: "011" },
//   { location: "rooiberg", code: "014" },
//   { location: "rooidraai", code: "049" },
//   { location: "rooigrond", code: "018" },
//   { location: "roossenekal", code: "013" },
//   { location: "rosebank", code: "011" },
//   { location: "rosebank", code: "010" },
//   { location: "rosedene", code: "023" },
//   { location: "rosendal", code: "058" },
//   { location: "rosetta", code: "033" },
//   { location: "rossouw", code: "045" },
//   { location: "rothdene", code: "016" },
//   { location: "rottanglaagte", code: "044" },
//   { location: "rouxville", code: "051" },
//   { location: "rouxville farm lines / plaaslyne", code: "05572" },
//   { location: "rust de winter", code: "012" },
//   { location: "rustenburg", code: "014" },
//   { location: "rysmierbult", code: "018" },
//   { location: "sabie", code: "013" },
//   { location: "sada", code: "040" },
//   { location: "saldanha", code: "022" },
//   { location: "samrand", code: "011" },
//   { location: "samrand", code: "010" },
//   { location: "sannieshof", code: "018" },
//   { location: "sannieshof farm lines / plaaslyne", code: "014472" },
//   { location: "santoy", code: "053" },
//   { location: "saron", code: "023" },
//   { location: "sasolburg", code: "016" },
//   { location: "schagen", code: "013" },
//   { location: "schmidtsdrift", code: "053" },
//   { location: "schuitdrift", code: "054" },
//   { location: "schweizer-reneke", code: "053" },
//   { location: "scottburgh", code: "039" },
//   { location: "sebokeng", code: "016" },
//   { location: "secunda", code: "017" },
//   { location: "sedgefield", code: "044" },
//   { location: "sekhukhune", code: "013" },
//   { location: "seleka", code: "014" },
//   { location: "selosesha", code: "051" },
//   { location: "selosesha farm lines / plaaslyne", code: "05187192" },
//   { location: "senekal", code: "058" },
//   { location: "senlac", code: "053932" },
//   { location: "sentrum", code: "014" },
//   { location: "senwabarana", code: "015" },
//   { location: "senwamokgope", code: "015" },
//   { location: "sepanapudi", code: "015" },
//   { location: "seshego", code: "015" },
//   { location: "setlagole", code: "018" },
//   { location: "setlagole farm lines / plaaslyne", code: "053982" },
//   { location: "setotolwane", code: "015" },
//   { location: "settlers", code: "014" },
//   { location: "seven oaks", code: "033" },
//   { location: "sevontein", code: "033" },
//   { location: "seymour", code: "040" },
//   { location: "shakaskraal", code: "032" },
//   { location: "shatale", code: "013" },
//   { location: "shayandima", code: "015" },
//   { location: "sheepmoor", code: "017" },
//   { location: "shongwe mission", code: "013" },
//   { location: "sibasa", code: "015" },
//   { location: "sibhayi", code: "035" },
//   { location: "sidu", code: "013" },
//   { location: "silkaatskop", code: "014" },
//   { location: "silwerkrans", code: "014" },
//   { location: "simon's town / simonstad", code: "021" },
//   { location: "simpkinsvale", code: "013" },
//   { location: "sinthumile", code: "015" },
//   { location: "sir lowry's pass", code: "021" },
//   { location: "siyabuswa", code: "013" },
//   { location: "siyathuthuka", code: "013" },
//   { location: "sizabantu", code: "032" },
//   { location: "skeerpoort", code: "012" },
//   { location: "skilpadfontein", code: "012" },
//   { location: "skuinsdrif", code: "014" },
//   { location: "skuinsdrif farm lines / plaaslyne", code: "0142592" },
//   { location: "skukuza", code: "013" },
//   { location: "slurry", code: "018" },
//   { location: "smithfield", code: "051" },
//   { location: "smithfield farm lines / plaaslyne", code: "05562" },
//   { location: "soekmekaar", code: "015" },
//   { location: "somarobogo", code: "013" },
//   { location: "somerset east/-oos", code: "042" },
//   { location: "somerset west/-wes", code: "021" },
//   { location: "soshanguve", code: "012" },
//   { location: "soutbos", code: "053932" },
//   { location: "southbroom", code: "039" },
//   { location: "soutpan", code: "051" },
//   { location: "sovenga", code: "015" },
//   { location: "spitskop", code: "049" },
//   { location: "spring valley", code: "045" },
//   { location: "springbok", code: "027" },
//   { location: "springbokvlakte", code: "049" },
//   { location: "springfontein", code: "051" },
//   { location: "springfontein farm lines / plaaslyne", code: "051782" },
//   { location: "springs", code: "011" },
//   { location: "st francis bay", code: "042" },
//   { location: "st helena bay", code: "022" },
//   { location: "st lucia", code: "035" },
//   { location: "st michael's on sea", code: "039" },
//   { location: "standerton", code: "017" },
//   { location: "stanford", code: "028" },
//   { location: "stanger", code: "032" },
//   { location: "stanger farm lines / plaaslyne", code: "053952" },
//   { location: "steekdoringd", code: "053" },
//   { location: "steelpoort", code: "013" },
//   { location: "steenbokpan", code: "014" },
//   { location: "steenkampskraal", code: "027" },
//   { location: "steinkopf", code: "027" },
//   { location: "stella", code: "053" },
//   { location: "stella farm lines / plaaslyne", code: "053982" },
//   { location: "stellenbosch", code: "021" },
//   { location: "sterkrivier", code: "015" },
//   { location: "sterkspruit", code: "051" },
//   { location: "sterkspruit farm lines / plaaslyne", code: "05582" },
//   { location: "sterkstroom", code: "045" },
//   { location: "steunmekaar", code: "051732" },
//   { location: "steynsburg", code: "048" },
//   { location: "steynsplaas", code: "05462" },
//   { location: "steynsrus", code: "056" },
//   { location: "steytlerville", code: "049" },
//   { location: "stilbaai", code: "028" },
//   { location: "stilfontein", code: "018" },
//   { location: "stoepies", code: "049" },
//   { location: "stoffberg", code: "013" },
//   { location: "stilbaai", code: "028" },
//   { location: "stilfontein", code: "018" },
//   { location: "stoepies", code: "049" },
//   { location: "stoffberg", code: "013" },
//   { location: "stompneusbaai", code: "022" },
//   { location: "stormsrivier", code: "042" },
//   { location: "straighthardt", code: "015" },
//   { location: "strand", code: "021" },
//   { location: "struisbaai", code: "028" },
//   { location: "strydenburg", code: "053" },
//   { location: "strydenburg farm lines / plaaslyne", code: "053682" },
//   { location: "studtis", code: "049" },
//   { location: "stutterheim", code: "043" },
//   { location: "sulenkama", code: "047" },
//   { location: "sundra", code: "013" },
//   { location: "supingstad", code: "018" },
//   { location: "suswe", code: "015" },
//   { location: "sutherland", code: "023" },
//   { location: "suurbraak", code: "028" },
//   { location: "swartdamstad", code: "012" },
//   { location: "swartfontein", code: "018" },
//   { location: "swartklip (np)", code: "014" },
//   { location: "swartkops", code: "033" },
//   { location: "swartruggens", code: "014" },
//   { location: "swartruggens farm lines / plaaslyne", code: "014262" },
//   { location: "swellendam", code: "028" },
//   { location: "swempoort", code: "045" },
//   { location: "tabankulu", code: "039" },
//   { location: "tamposstad", code: "014" },
//   { location: "tarentaalrand", code: "015" },
//   { location: "tarkastad", code: "045" },
//   { location: "taung", code: "053" },
//   { location: "taung farm lines / plaaslyne", code: "053992" },
//   { location: "telleriepan", code: "054902" },
//   { location: "temba", code: "012" },
//   { location: "tembisa", code: "011" },
//   { location: "thaba nchu", code: "051" },
//   { location: "thaba phatshawa", code: "051" },
//   { location: "thabazimbi", code: "014" },
//   { location: "thandukwazi", code: "017" },
//   { location: "the haven", code: "047" },
//   { location: "theunissen", code: "057" },
//   { location: "theunissen farm lines / plaaslyne", code: "05772" },
//   { location: "thohoyandou", code: "015" },
//   { location: "tholongwe", code: "015" },
//   { location: "thornhill", code: "042" },
//   { location: "thornville junction", code: "033" },
//   { location: "three sisters", code: "053" },
//   { location: "thulamahashe", code: "013" },
//   { location: "thuthukani", code: "017" },
//   { location: "tierpoort", code: "051" },
//   { location: "tina falls", code: "047" },
//   { location: "tinmyne", code: "015" },
//   { location: "tlhabane", code: "014" },
//   { location: "tolwe", code: "014" },
//   { location: "tongaat", code: "032" },
//   { location: "tontelbos", code: "054" },
//   { location: "tontelbos farm lines", code: "054602" },
//   { location: "tosca", code: "053" },
//   { location: "tosca farm lines / plaaslyne", code: "053932" },
//   { location: "touwsrivier", code: "023" },
//   { location: "trichardtsdal", code: "015" },
//   { location: "trompsburg", code: "051" },
//   { location: "tshakuma", code: "015" },
//   { location: "tshaulu", code: "015" },
//   { location: "tshidilamolomo", code: "018" },
//   { location: "tshikondeni", code: "015" },
//   { location: "tshipise", code: "015" },
//   { location: "tsitsikamma", code: "042" },
//   { location: "tsolo", code: "047" },
//   { location: "tsomo", code: "047" },
//   { location: "tswelelange", code: "018" },
//   { location: "tubatse", code: "013" },
//   { location: "tugela ferry", code: "033" },
//   { location: "tugela mouth", code: "032" },
//   { location: "tuinplaas", code: "014" },
//   { location: "tulbagh", code: "023" },
//   { location: "tweeling", code: "058" },
//   { location: "tweespruit", code: "051" },
//   { location: "tweespruit farm lines / plaaslyne", code: "051962" },
//   { location: "tzaneen", code: "015" },
//   { location: "ubombo", code: "035" },
//   { location: "ugie", code: "045" },
//   { location: "uitenhage", code: "041" },
//   { location: "uitkyk", code: "014" },
//   { location: "ulco", code: "053" },
//   { location: "ulco farm lines / plaaslyne", code: "053862" },
//   { location: "ulundi", code: "035" },
//   { location: "umbumbulu", code: "031" },
//   { location: "umgababa", code: "031" },
//   { location: "umkomaas", code: "039" },
//   { location: "umtata", code: "047" },
//   { location: "umtentweni", code: "039" },
//   { location: "umzimkulu", code: "039" },
//   { location: "umzinto", code: "039" },
//   { location: "umzumbe", code: "039" },
//   { location: "underberg", code: "033" },
//   { location: "uniondale", code: "044" },
//   { location: "upington", code: "054" },
//   { location: "uthokozani", code: "013" },
//   { location: "utrecht", code: "034" },
//   { location: "vaaltyn", code: "015" },
//   { location: "vaalwater", code: "014" },
//   { location: "val", code: "017" },
//   { location: "van reenen", code: "058" },
//   { location: "van zylsrus", code: "053" },
//   { location: "vanderbijlpark", code: "016" },
//   { location: "vanderkloof", code: "053" },
//   { location: "vandyksdrif", code: "013" },
//   { location: "vanrhynsdorp", code: "027" },
//   { location: "van stadensrus", code: "051" },
//   { location: "van stadensrus farm lines / plaaslyne", code: "052332" },
//   { location: "vanwyksdorp", code: "028" },
//   { location: "vanwyksvlei", code: "053" },
//   { location: "vanwyksvlei farm lines / plaaslyne", code: "0533832" },
//   { location: "velddrif", code: "022" },
//   { location: "ventersburg", code: "057" },
//   { location: "ventersdorp", code: "018" },
//   { location: "venterstad", code: "051" },
//   { location: "vereeniging", code: "016" },
//   { location: "verena", code: "013" },
//   { location: "vergelee", code: "053" },
//   { location: "vergelee farm lines / plaaslyne", code: "0539362" },
//   { location: "verkeerdevlei", code: "051" },
//   { location: "verkykerskop", code: "058" },
//   { location: "verlatekloof", code: "023" },
//   { location: "vermaas", code: "014492" },
//   { location: "verneukpan", code: "054602" },
//   { location: "verplig", code: "053922" },
//   { location: "verulam", code: "032" },
//   { location: "victoria west", code: "053" },
//   { location: "victoria west farm lines / plaaslyne", code: "053612" },
//   { location: "vierfontein", code: "018" },
//   { location: "viljoensdrif", code: "016" },
//   { location: "viljoenskroon", code: "056" },
//   { location: "villiers", code: "058" },
//   { location: "villiersdorp", code: "028" },
//   { location: "vioolsdrift", code: "027" },
//   { location: "virginia", code: "057" },
//   { location: "vivo", code: "015" },
//   { location: "vleiland", code: "023" },
//   { location: "volksrust", code: "017" },
//   { location: "volop", code: "05472" },
//   { location: "voltargo", code: "013" },
//   { location: "vongani", code: "015" },
//   { location: "voortrekkerstrand", code: "039" },
//   { location: "vosburg", code: "053" },
//   { location: "vosburg farm lines / plaaslyne", code: "0536732" },
//   { location: "vostershoop", code: "053" },
//   { location: "vostershoop farm lines / plaaslyne", code: "053922" },
//   { location: "vrede", code: "058" },
//   { location: "vredefort", code: "056" },
//   { location: "vredenburg", code: "022" },
//   { location: "vredendal", code: "027" },
//   { location: "vrouenspan", code: "054" },
//   { location: "vrouenspan farm lines/plaaslyne", code: "054902" },
//   { location: "vryburg", code: "053" },
//   { location: "vryheid", code: "034" },
//   { location: "vuwani", code: "015" },
//   { location: "vuyani", code: "015" },
//   { location: "waenhuiskrans", code: "028" },
//   { location: "wakkerstroom", code: "017" },
//   { location: "wallekraal", code: "027" },
//   { location: "warburton", code: "017" },
//   { location: "warden", code: "058" },
//   { location: "warden farm lines / plaaslyne", code: "058642" },
//   { location: "warmbad", code: "014" },
//   { location: "warrenton", code: "053" },
//   { location: "wartburg", code: "033" },
//   { location: "wasbank", code: "034" },
//   { location: "waterval (kzn)", code: "034" },
//   { location: "waterval boven", code: "013" },
//   { location: "weenen", code: "036" },
//   { location: "warden", code: "058" },
//   { location: "warden", code: "058" },
//   { location: "welgevonden", code: "012" },
//   { location: "welkom", code: "057" },
//   { location: "wellington", code: "021" },
//   { location: "welverdiend", code: "018" },
//   { location: "wepener", code: "051" },
//   { location: "wepener farm lines / plaaslyne", code: "05232" },
//   { location: "wesley", code: "040" },
//   { location: "wesselsbron", code: "057" },
//   { location: "westminster", code: "051" },
//   { location: "westminster farm lines / plaaslyne", code: "051952" },
//   { location: "weza", code: "039" },
//   { location: "wielkolksleegte", code: "0533912" },
//   { location: "williston", code: "053" },
//   { location: "williston farm lines / plaaslyne", code: "0533912" },
//   { location: "willowmore", code: "044" },
//   { location: "willowvale", code: "047" },
//   { location: "winburg", code: "051" },
//   { location: "winburg farm lines / plaaslyne", code: "05242" },
//   { location: "windsorton", code: "053" },
//   { location: "winterton", code: "036" },
//   { location: "winterveld", code: "012" },
//   { location: "witbank", code: "013" },
//   { location: "witklipdrif", code: "027" },
//   { location: "witrivier", code: "013" },
//   { location: "witsand", code: "028" },
//   { location: "witteklip", code: "049" },
//   { location: "wolfhok", code: "027" },
//   { location: "wolmaransstad", code: "018" },
//   { location: "wolseley", code: "023" },
//   { location: "wolwefontein", code: "049" },
//   { location: "wolwekrans", code: "013" },
//   { location: "worcester", code: "023" },
//   { location: "wuppertal", code: "027" },
//   { location: "wyke", code: "023" },
//   { location: "yzerfontein", code: "022" },
//   { location: "zastron", code: "051" },
//   { location: "zastron farm lines / plaaslyne", code: "05542" },
//   { location: "zebediela", code: "015" },
//   { location: "zeerust", code: "018" },
//   { location: "zoar", code: "028" },
//   { location: "zuurbekom", code: "011" },
//   { location: "zwelitsha", code: "040" },
// ];
